# Generated by Django 5.0.6 on 2026-02-12 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domain', models.CharField(choices=[('1st Year Student', '1st Year Student'), ('2nd Year Student', '2nd Year Student'), ('3rd/4th Year Student', '3rd Year Student'), ('Working Professional', 'Working Professional'), ('Beginner', 'Beginner')], max_length=50)),
                ('rating', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Average'), (1, 'Poor')])),
                ('issue_type', models.CharField(blank=True, max_length=100)),
                ('issue_description', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('Definitely Yes', 'Definitely Yes'), ('Probably Yes', 'Probably Yes'), ('Maybe', 'Maybe'), ('Probably No', 'Probably No'), ('No', 'No')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
