# Generated by Django 5.0.6 on 2026-02-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='issue_description',
        ),
    ]
